import { IUseNavigateDetailFoodParams } from "@/@core/useCases/foods/UseNavigateDetailFood"
import useGetAllPresentation from "@/presentation/foods/main"
import Head from "next/head"

const MainFoods = () => {
  const { foods, navigateToDetail, navigateToCreate } = useGetAllPresentation()

  return (
    <>
      <Head>
        <title>Foods</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col h-full">
        <main >
          <button className="rounded-md bg-blue-500 text-white p-2 mt-2 mb-4 w-1/3" onClick={navigateToCreate}>Cadastrar</button>

          <div className="grid grid-cols-3 gap-3">
            {foods.map((food, index) => {
              return (
                <section className="flex flex-col p-4 items-center justify-center border border-gray-100 rounded-2xl" key={`list-${index}`}>
                  <h1 className="text-2xl text-gray-800 font-bold">{food.name}</h1>
                  <p className="text-xl text-gray-600">{food.name}</p>
                  <p className="text-xl text-gray-600"><span className="text-sm">R$</span>{food.price}</p>
                  <button
                    className="rounded-md bg-blue-500 text-white p-2 mt-2 w-full"
                    onClick={() =>
                      navigateToDetail(food as IUseNavigateDetailFoodParams)
                    }
                  >
                    Detalhar
                  </button>
                </section>
              )
            })}
          </div>

        </main>
        <footer className="flex justify-center">
          <p>@Foods</p>
        </footer>
      </div>
    </>
  )
}

export default MainFoods
