import { IUseNavigateDetailFoodParams } from "@/@core/useCases/foods/UseNavigateDetailFood"
import useGetAllPresentation from "@/presentation/main"
import Head from "next/head"
import localFont from "next/font/local"
import styles from "@/styles/Home.module.css"

const geistSans = localFont({
  src: "../../pages/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "../../pages/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

const MainFoods = () => {
  const { foods, navigateToDetail } = useGetAllPresentation()

  return (
    <>
      <Head>
        <title>Foods</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <div className={styles.ctas}>
            {foods.map((food) => {
              return (
                <section>
                  <h1>{food.name}</h1>
                  <p>{food.name}</p>
                  <p>{food.price}</p>
                  <button
                    onClick={() =>
                      navigateToDetail(food as IUseNavigateDetailFoodParams)
                    }
                  >
                    Detalhar
                  </button>
                </section>
              )
            })}
          </div>
        </main>
        <footer className={styles.footer}>
          <p>@Foods</p>
        </footer>
      </div>
    </>
  )
}

export default MainFoods
